### ISSUE TITLE
OS X: test manual build

### ISSUE THREAD

**Issue by smokhov** [OpenISS/OpenISS#14]
Folks, please test see if you are able to rebuild the submodules of OpenISS (libfreenect, libfreenect2, ogl, opencv, tinyosc, openFrameworks) on OS X manually or using their build instructions/scripts Try running their examples. Report progress here. This is NOT urgent.

**Comment by jashanj0tsingh** [comment]
I tried `cmake libfreenect` and it failed to build and I am attaching the CMake log and error file with this comment.
[CMakeError.log](https://github.com/OpenISS/OpenISS/files/1541088/CMakeError.log)
[CMakeOutput.log](https://github.com/OpenISS/OpenISS/files/1541089/CMakeOutput.log)

**Comment by smokhov** [comment]
@jashanj0tsingh, so it cannot find `pthreads` library. Need to make it find it.

> ld: library not found for -lpthreads

**Comment by jashanj0tsingh** [comment]
Are you sure? To me it seems an issue with missing "libusb", I brewed
installed and it seems to be working. Should I be looking around for the
"pthread" library? Below is the current terminal output.


-- Operating system is Apple MacOS X

-- Got System Processor x86_64

-- libfreenect will be installed to /usr/local

-- Headers will be installed to /usr/local/include/libfreenect

-- Libraries will be installed to /usr/local/lib

-- Found libusb-1.0:

--  - Includes: /usr/local/include/libusb-1.0

--  - Libraries: /usr/local/lib/libusb-1.0.dylib

-- Configuring done

CMake Warning (dev):

  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake

  --help-policy CMP0042" for policy details.  Use the cmake_policy command
to

  set the policy and suppress this warning.


  MACOSX_RPATH is not specified for the following targets:


   fakenect

   freenect

   freenect_sync


This warning is for project developers.  Use -Wno-dev to suppress it.


-- Generating done

-- Build files have been written to: /Users/jashanjotsingh/Documents/OpenISS

**Comment by smokhov** [comment]
> Are you sure?

It came from your log file. So it seems working for you now? Can you try to run fakenect?

**Comment by jashanj0tsingh** [comment]
For fakenect, tinyosc and openFrameworks it says that missing
CMakeFiles.txt. So I am. not sure about that for now.

**Comment by smokhov** [comment]
`fakenect` is included when `libfreenect` is successfully built, it's `fakenect-record` tool would be in `bin/` and the libraries in `lib/fakenect`. You would need to manipulate the path for it to find the `lib/fakenect` as a driver to replay the data set using `freenect-glview` following their example on the github front page.

**Comment by laihaotao** [comment]
I can build `libfreenect` and `libfreenect2` successfully, my laptop already has `opencv`. For that `tinyosc` and `ogl` I can't find any build instruction (through the given link, I will try them later) and now trying the `openFrameworks`.

**Comment by jashanj0tsingh** [comment]
I have been trying the `DYLD_LIBRARAY_PATH=/usr/local/bin/fakenect` `FAKENECT_PATH=Path to recorded video provided by you.` `freenect-glview` and almost every other workaround also from [here.](https://github.com/OpenKinect/libfreenect#fakenect) Remember these work without flags too if sudo make installed however the output remained same for me. It said `Kinect devices found = 0`.
I did try [this](https://openkinect.org/wiki/Getting_Started#Manual_Build_under_OSX) too. Manual Build for OSX and did encounter both the situations mentioned. 

The only thing I want to try is record a feed using `fakenect-record` binary and then feed the `session` to the entire argument.

**Comment by smokhov** [comment]
@laihaotao 

> I can build libfreenect and libfreenect2 successfully, my laptop already has opencv.

Good. Can you run their examples?

> For that tinyosc and ogl I can't find any build instruction

- https://github.com/OpenISS/OpenISS/blob/c7caf95cfbb501a834c4af29a9bf0da2d2135270/src/scripts/build.sh#L30
- https://github.com/OpenISS/OpenISS/blob/c7caf95cfbb501a834c4af29a9bf0da2d2135270/src/scripts/build.sh#L165
- http://www.opengl-tutorial.org/beginners-tutorials/tutorial-1-opening-a-window/

> For openFrameworks, I don't try to build them from source code, since the source code is so large. I download the pre-build version. And follow the instruction here I can successfully compile all examples.

Excellent, can you run some of the video, graphics, ofxKinect, ofxOpenCv and other examples?

**Comment by smokhov** [comment]
@jashanj0tsingh 

> I have been trying the DYLD_LIBRARY_PATH=/usr/local/bin/fakenect

This seems wrong; let's correct this first. I'd expect this path to lead to fakenect.dylib either from your build directory or something along the lines of /usr/local/lib

**Comment by smokhov** [comment]
It was sufficiently tested by @laihaotao , @jashanj0tsingh , myself and @kostapsimoulis -- we will continue M1 testing in #72.
