### ISSUE TITLE
Java: WS: add proper src/api/java/openiss/ws/soap/client/OpenISSSOAPClient.java

### ISSUE THREAD

**Issue by smokhov** [OpenISS/OpenISS#50]
Per PR #48. Not urgent.

**Comment by kostapsimoulis** [comment]
It was just refactoring. SOAP Client was never implemented in Java, it was done with NodeJS. On hava we only had the Endpoint

https://github.com/OpenISS/OpenISS/blob/master/src/api/java/openiss/ws/soap/endpoint/ServicePublisher.java

The file that was removed was just an incomplete code that never got finalized and tested. It was removing during refactoring.

Here are the contents of the file:
https://github.com/OpenISS/OpenISS/blob/ad79b04219cf2ddb1c81ba33ef7a1728e47f34d3/src/api/java/openiss/ws/soap/client/OpenISSSOAPClient.java

It was just a clean. @smokhov can we close this ticket?

**Comment by smokhov** [comment]
OK, closing. I was hoping it'd be useful to the distributed systems students at some point.
