### ISSUE TITLE
Java: WS: support depth2/color2, etc. for Kinect 2

### ISSUE THREAD

**Issue by smokhov** [OpenISS/OpenISS#51]

**Comment by smokhov** [comment]
Eric progressed on this in the `add-libfreenect2` branch.

**Comment by kostapsimoulis** [comment]
I have no Kinect V2 to use and test. @smokhov please let me know if you have one that I can borrow

**Comment by smokhov** [comment]
This branch was merged and we should not technically have color2 and depth2 API. It should always be /color and /depth only and the device type should be selected via a different API. To be tackled separately. Closing.
